 name: Manually Deploy to heroku

on: workflow_dispatch

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12

        with:

          heroku_api_key: ${{secrets.HEROKU_API_KEY}}

          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}

          heroku_email: ${{secrets.HEROKU_EMAIL}}

          usedocker: true

          docker_heroku_process_type: worker

          stack: "container"

          region: "eu"

        env:

          HD_APP_ID: ${{secrets.APP_ID}}

          HD_API_HASH: ${{secrets.API_HASH}}

          HD_TG_BOT_TOKEN: ${{secrets.TG_BOT_TOKEN}}

          HD_AUTH_CHANNEL: ${{secrets.AUTH_CHANNEL}}

          HD_OWNER_ID: ${{secrets.OWNER_ID}}

          HD_CHUNK_SIZE: ${{secrets.CHUNK_SIZE}}

          HD_EDIT_SLEEP_TIME_OUT: ${{secrets.EDIT_SLEEP_TIME_OUT}} 

          HD_MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START: ${{secrets.MAX_TIME_TO_WAIT_FOR_TORRENTS_TO_START}}

          HD_TG_MAX_FILE_SIZE: ${{secrets.TG_MAX_FILE_SIZE}}

          HD_MAX_TG_SPLIT_FILE_SIZE: ${{secrets.MAX_TG_SPLIT_FILE_SIZE}}

          HD_ARIA_TWO_STARTED_PORT: ${{secrets.ARIA_TWO_STARTED_PORT}}

          HD_UPLOAD_AS_DOC: ${{secrets.UPLOAD_AS_DOC}}
